server:
  port: 14443
  ssl:
    protocol: TLS
    enabled-protocols: TLSv1.3
    bundle: eudi-rp

spring:
  application:
    name: eudi-rp-mock
  main:
    banner-mode: off
  ssl:
    bundle:
      pem:
        eudi-rp:
          key:
            alias: eudi-rp.localhost
          keystore:
            certificate: classpath:eudi-rp.localhost.crt
            private-key: classpath:eudi-rp.localhost.key
          truststore:
            certificate: classpath:eudi-ca.localhost.crt
        eudi-issuer-ca:
          truststore:
            certificate: classpath:eudi-ca.localhost.crt
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: configprops,env,health,info
  info:
    git:
      mode: full
    java:
      enabled: true
    os:
      enabled: true

eudi:
  rp:
    client-id: eudi-rp.localhost
    base-url: https://eudi-rp.localhost:14443
  rp-backend:
    base-url: https://eudi-rp-backend.localhost:15443
    request-endpoint-url: https://eudi-rp-backend.localhost:15443/request
    response-endpoint-url: https://eudi-rp-backend.localhost:15443/response
  wallet:
    authorization-url: https://eudi-wallet.localhost:16443/authorize
